"""Generic metric-feature computation module."""

from flow_engine.metric_feature.models import (
    DataSet,
    FeatureDefinition,
    FeaturePlan,
    FeatureSnapshot,
    MetricDefinition,
    MetricOperation,
    MetricPlan,
    PipelineContract,
    PipelineContext,
    PipelineOutput,
    PipelineStage,
    RuleClause,
    RuleDefinition,
    RuleMatch,
    StageContract,
    default_pipeline_contract,
)
from flow_engine.metric_feature.service import (
    compact_dataset_for_plan,
    compute_features,
    dataset_from_raw,
    enrich_dataset_with_side_input,
    evaluate_rules,
    load_feature_plan_from_dict,
    load_metric_plan_from_dict,
    load_rules_from_dict,
    load_scenario_config_from_dict,
    pipeline_contract,
    run_pipeline_from_dict_name,
    run_pipeline,
)

__all__ = [
    "DataSet",
    "MetricOperation",
    "MetricDefinition",
    "MetricPlan",
    "FeatureDefinition",
    "FeaturePlan",
    "FeatureSnapshot",
    "RuleClause",
    "RuleDefinition",
    "RuleMatch",
    "PipelineStage",
    "StageContract",
    "PipelineContract",
    "default_pipeline_contract",
    "PipelineContext",
    "PipelineOutput",
    "compute_features",
    "compact_dataset_for_plan",
    "enrich_dataset_with_side_input",
    "evaluate_rules",
    "run_pipeline",
    "run_pipeline_from_dict_name",
    "dataset_from_raw",
    "pipeline_contract",
    "load_scenario_config_from_dict",
    "load_metric_plan_from_dict",
    "load_feature_plan_from_dict",
    "load_rules_from_dict",
]
